<?php

namespace Database\Factories;

use App\Enums\PostStatus;
use App\Models\Post;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Post>
 */
class PostFactory extends Factory
{
    protected $model = Post::class;

    public function definition(): array
    {
        return [
            'uuid' => $this->faker->uuid(),
            'slug' => null, // generated by model boot
            'author_type' => 'App\Models\Citizen',
            'author_id' => 1,
            'title' => $this->faker->sentence(6),
            'subtitle' => $this->faker->optional(0.5)->sentence(8),
            'excerpt' => $this->faker->paragraph(2),
            'body' => '<p>' . $this->faker->paragraphs(3, true) . '</p>',
            'featured_image_url' => null,
            'status' => PostStatus::Draft,
            'published_at' => null,
            'allow_comments' => true,
            'is_promoted' => false,
            'credit_spent' => 0,
        ];
    }

    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => PostStatus::Published,
            'published_at' => now()->subHour(),
        ]);
    }
}
