<?php

namespace App\Http\Controllers\Standalone;

use App\Http\Controllers\Controller;
use App\Jobs\MatchPoliticianToElectionData;
use App\Models\CandidateMatchReview;
use App\Models\Politician;
use App\Services\PoliticianElectionMatcher;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Storage;

/**
 * Admin candidate-match review queue and election candidate imports.
 *
 * Split out of AdminController. Covers the pending-match review queue, bulk
 * approve/reject, single approve/reject/retry, and the elections:import-candidates
 * Artisan runner (file path or upload). Politician-to-election auto-matching is
 * dispatched via MatchPoliticianToElectionData.
 */
class AdminCandidateMatchController extends Controller
{
    /**
     * Show pending candidate match reviews generated by automatic matching.
     */
    public function candidateMatchReviews(Request $request)
    {
        $statusFilter = $request->query('status', 'pending');
        $allowedStatuses = [
            CandidateMatchReview::STATUS_PENDING,
            CandidateMatchReview::STATUS_APPROVED,
            CandidateMatchReview::STATUS_REJECTED,
        ];

        $query = CandidateMatchReview::with(['politician.user', 'candidateRecord'])->latest();

        if (in_array($statusFilter, $allowedStatuses, true)) {
            $query->where('status', $statusFilter);
        }

        if ($search = trim((string) $request->query('q', ''))) {
            $query->where(function ($q) use ($search) {
                $q->whereHas('politician', function ($pq) use ($search) {
                    $pq->where('full_name', 'like', "%{$search}%")
                        ->orWhere('political_office', 'like', "%{$search}%");
                })->orWhereHas('candidateRecord', function ($cq) use ($search) {
                    $cq->where('full_name', 'like', "%{$search}%")
                        ->orWhere('political_office', 'like', "%{$search}%");
                });
            });
        }

        $reviews = $query->paginate(30)->withQueryString();

        $stats = [
            'pending' => CandidateMatchReview::where('status', CandidateMatchReview::STATUS_PENDING)->count(),
            'approved' => CandidateMatchReview::where('status', CandidateMatchReview::STATUS_APPROVED)->count(),
            'rejected' => CandidateMatchReview::where('status', CandidateMatchReview::STATUS_REJECTED)->count(),
        ];

        return view('standalone.admin.candidate-match-reviews', compact('reviews', 'stats', 'statusFilter'));
    }

    /**
     * Bulk approve or reject pending candidate match reviews.
     */
    public function bulkCandidateMatchAction(Request $request, PoliticianElectionMatcher $matcher)
    {
        $validated = $request->validate([
            'action' => ['required', 'in:approve,reject'],
            'review_ids' => ['required', 'array', 'min:1'],
            'review_ids.*' => ['integer', 'exists:candidate_match_reviews,id'],
        ]);

        $action = (string) $validated['action'];
        $reviewIds = collect($validated['review_ids'])
            ->map(static fn ($id) => (int) $id)
            ->unique()
            ->values();

        $reviews = CandidateMatchReview::whereIn('id', $reviewIds)
            ->where('status', CandidateMatchReview::STATUS_PENDING)
            ->get();

        if ($reviews->isEmpty()) {
            return back()->withErrors(['error' => 'No pending reviews were selected.']);
        }

        $updated = 0;
        $admin = auth()->user();
        $label = $action === 'approve' ? 'Bulk approved by admin' : 'Bulk rejected by admin';

        foreach ($reviews as $review) {
            if ($action === 'approve') {
                $matcher->approveReview($review, $admin, $label);
            } else {
                $matcher->rejectReview($review, $admin, $label);
            }
            $updated++;
        }

        $noun = $updated === 1 ? 'match' : 'matches';

        return back()->with('success', "Bulk {$action}d {$updated} candidate {$noun}.");
    }

    /**
     * Run election candidate import from Admin UI.
     */
    public function importElectionCandidates(Request $request)
    {
        $request->validate([
            'source' => ['required', 'string', 'max:64'],
            'file' => ['nullable', 'string', 'max:255', 'required_without:file_upload'],
            'file_upload' => ['nullable', 'file', 'mimes:json,txt', 'max:10240', 'required_without:file'],
            'dry_run' => ['nullable', 'boolean'],
        ]);

        $importFile = (string) $request->input('file', '');

        if ($request->hasFile('file_upload')) {
            $upload = $request->file('file_upload');
            $safeName = 'candidate-import-' . now()->format('Ymd-His') . '-' . uniqid('', true) . '.json';
            $storedRelative = $upload->storeAs('imports/uploads', $safeName, 'local');
            $importFile = Storage::disk('local')->path((string) $storedRelative);
        }

        $args = [
            '--source' => (string) $request->input('source'),
            '--file' => $importFile,
        ];

        if ($request->boolean('dry_run')) {
            $args['--dry-run'] = true;
        }

        $exitCode = Artisan::call('elections:import-candidates', $args);
        $output = trim(Artisan::output());

        if ($exitCode !== 0) {
            return back()
                ->withErrors(['error' => $output !== '' ? $output : 'Import failed.'])
                ->withInput();
        }

        return back()
            ->with('success', 'Election candidate import completed.')
            ->with('import_output', $output);
    }

    /**
     * Approve a pending candidate match review and create the identity link.
     */
    public function approveCandidateMatch(CandidateMatchReview $review, PoliticianElectionMatcher $matcher)
    {
        if ($review->status !== CandidateMatchReview::STATUS_PENDING) {
            return back()->withErrors(['error' => 'This review has already been resolved.']);
        }

        $matcher->approveReview($review, auth()->user(), 'Approved by admin');

        return back()->with('success', 'Candidate match approved and linked.');
    }

    /**
     * Reject a pending candidate match review.
     */
    public function rejectCandidateMatch(Request $request, CandidateMatchReview $review, PoliticianElectionMatcher $matcher)
    {
        if ($review->status !== CandidateMatchReview::STATUS_PENDING) {
            return back()->withErrors(['error' => 'This review has already been resolved.']);
        }

        $request->validate([
            'reason' => ['nullable', 'string', 'max:500'],
        ]);

        $matcher->rejectReview($review, auth()->user(), $request->input('reason', 'Rejected by admin'));

        return back()->with('success', 'Candidate match rejected.');
    }

    /**
     * Re-run automatic matching for a specific politician.
     */
    public function retryCandidateMatch(Politician $politician)
    {
        MatchPoliticianToElectionData::dispatch($politician->id);

        return back()->with('success', 'Re-match job queued for ' . $politician->full_name . '.');
    }
}
