<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Marketing Drafts Digest — {{ config('app.name', 'U9itus') }}</title>
<style>
  body { margin: 0; padding: 0; background-color: #0f172a; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #e2e8f0; }
  .wrapper { max-width: 640px; margin: 32px auto; padding: 0 16px; }
  .card { background-color: #1e293b; border: 1px solid #334155; border-radius: 16px; overflow: hidden; }
  .header { padding: 28px 36px 22px; border-bottom: 1px solid #334155; background-color: #0f172a; }
  .logo { font-size: 28px; font-weight: 300; color: #ffffff; }
  .logo span { color: #34d399; font-weight: 700; }
  .tagline { margin-top: 6px; font-size: 12px; color: #64748b; letter-spacing: 1px; text-transform: uppercase; }
  .body { padding: 32px 36px; }
  h1 { margin: 0 0 12px; font-size: 24px; font-weight: 600; color: #ffffff; }
  p { margin: 0 0 14px; font-size: 15px; line-height: 1.65; color: #94a3b8; }
  .draft-card { background-color: #0f172a; border: 1px solid #334155; border-radius: 12px; padding: 18px 20px; margin: 14px 0; }
  .meta { display: flex; justify-content: space-between; gap: 12px; margin-bottom: 10px; font-size: 12px; color: #64748b; }
  .badge { display: inline-block; padding: 4px 10px; border-radius: 999px; border: 1px solid rgba(52, 211, 153, 0.25); background-color: rgba(16, 185, 129, 0.12); color: #6ee7b7; font-size: 11px; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; }
  .label { font-size: 11px; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; color: #64748b; margin-bottom: 4px; }
  .title { color: #e2e8f0; font-size: 16px; line-height: 1.5; margin: 4px 0 12px; }
  .title a { color: #e2e8f0; text-decoration: none; }
  .title a:hover { text-decoration: underline; }
  .link { font-size: 13px; color: #6ee7b7; }
  .footer { border-top: 1px solid #334155; padding: 18px 36px; text-align: center; }
  .footer p { margin: 0; font-size: 12px; color: #475569; }
</style>
</head>
<body>
<div class="wrapper">
  <div class="card">
    <div class="header">
      <div class="logo">u9<span>'</span>itus</div>
      <div class="tagline">Marketing Drafts Digest</div>
    </div>
    <div class="body">
      <h1>{{ $drafts->count() }} {{ $drafts->count() === 1 ? 'draft' : 'drafts' }} awaiting review</h1>
      <p>The marketing content agent auto-drafted the blog posts below from recent news and viral moments. Each is saved as <strong>pending approval</strong> and attributed to its politician, who reviews and publishes it from their dashboard. Nothing below is public yet.</p>

      @foreach ($drafts as $draft)
        @php
          $politician = $draft->politician;
          $sourceLabel = $draft->source_type->value === 'viral_moment' ? 'Viral moment' : 'News';
          $profileUrl = $politician && $politician->slug
              ? route('politician.public.show', $politician->slug)
              : null;
        @endphp
        <div class="draft-card">
          <div class="meta">
            <span class="badge">{{ $sourceLabel }}</span>
            <span>{{ $draft->created_at?->format('M j, Y g:i A') }}</span>
          </div>
          <div class="label">Politician</div>
          <div class="title">
            @if ($profileUrl)
              <a href="{{ $profileUrl }}">{{ $politician->full_name }}</a>
            @else
              {{ $politician?->full_name ?? 'Unknown' }}
            @endif
          </div>
          <div class="label">Drafted post</div>
          <div class="title">{{ $draft->generated_title ?? $draft->source_title ?? '(untitled)' }}</div>
          @if ($profileUrl)
            <div class="link"><a href="{{ $profileUrl }}">View politician profile →</a></div>
          @endif
        </div>
      @endforeach
    </div>
    <div class="footer">
      <p>You received this because you are a u9'itus platform admin. Generated by the marketing content agent.</p>
    </div>
  </div>
</div>
</body>
</html>