{{ config('app.name', 'U9itus') }} — Marketing Drafts Digest
=============================================================

{{ $drafts->count() }} {{ $drafts->count() === 1 ? 'draft' : 'drafts' }} awaiting review.

The marketing content agent auto-drafted the blog posts below from recent news
and viral moments. Each is saved as PENDING APPROVAL and attributed to its
politician, who reviews and publishes it from their dashboard. Nothing below is
public yet.

@foreach ($drafts as $index => $draft)
@php
  $politician = $draft->politician;
  $sourceLabel = $draft->source_type->value === 'viral_moment' ? 'Viral moment' : 'News';
  $profileUrl = $politician && $politician->slug
      ? route('politician.public.show', $politician->slug)
      : null;
@endphp
DRAFT {{ $index + 1 }}
  Source      : {{ $sourceLabel }}
  Drafted     : {{ $draft->created_at?->format('M j, Y g:i A') }}
  Politician  : {{ $politician?->full_name ?? 'Unknown' }}
  Post title  : {{ $draft->generated_title ?? $draft->source_title ?? '(untitled)' }}
  @if ($profileUrl)Profile     : {{ $profileUrl }}
  @endif
@endforeach

You received this because you are a u9'itus platform admin.
Generated by the marketing content agent.