@extends('layouts.generic')



@section('content')

    <section id="main" class="container">


        <div class="box">


<article>

<p>Head Enterprises SUBSCRIPTION TERMS AND CONDITIONS</p>
<p>The purpose of this Agreement (hereafter referred to as the "Agreement") is to set forth Head Enterprise Dial4dough.com subscription Terms and Conditions.</p>
<p>Terms and Conditions</p>
<p>This Agreement contains the complete terms and conditions that apply to your participation as an subscription in the subscription Program of Head Enterprises, and the establishment of links from your subscription web site to our web site Domain. As used in this Agreement, "we," "us." "our," or “Head Enterprises” means Head Enterprises and "you" or "your" means the subscription, and "Product" means any and all items offered for sale by us on the Head Enterprises web site.</p>
<p>THIS IS A LEGAL AGREEMENT BETWEEN YOU AND &lt;
    <Head Enterprises>>. BY CLICKING THE "I AGREE" BUTTON ON THE Subscription APPLICATION, YOU ARE AFFIRMATIVELY STATING THAT YOU HAVE READ THE Subscription AGREEMENT AND UNDERSTAND THE TERMS SET FORTH HEREIN AND ARE AFFIRMATIVELY INDICATING YOUR ACCEPTANCE OF THIS Subscription AGREEMENT AND YOU AGREE TO BE BOUND BY THE TERMS HEREOF.</p>
<ol>
    <li>Enrollment in the subscription Program.</li>
</ol>
<p>To begin the enrollment process, you will submit a completed subscription Application via our web site. Once your application has been approved, you will receive your subscription code and password to allow you to start marketing the Head Enterprises products. We may reject your application if we determine (in our sole discretion) that your site is unsuitable as an subscription for any reason, including, but not limited to, if your site incorporates images or content that is in any way unlawful, harmful, threatening, defamatory, obscene; harassing or racially, ethically, or otherwise objectionable;
    such as sites that facilitate illegal activity; depict sexually explicit images; promote violence; promote discrimination based on race, sex, religion, nationality, disability, sexual orientation, or age; promote illegal activities or incorporate any materials that infringe or assist others to infringe on any copyright, trademark, or other intellectual property rights (collectively "Content Restrictions").</p>
<ol>
    <li>Using Our Links on Your Site.</li>
</ol>
<p>Link means a hyperlink to the Head Enterprises web site that is copied and pasted from your individual password-protected subscription administration area on our site. If the HTML code is altered in any way after copying from that web page, we take no responsibility for you receiving credit for any sale. Any change you make may cause the tracking to no longer function correctly.</p>
<p>As a subscriber site ("subscription Site"), we will make available to you banners, button links to our web site and/or text links to our web site, containing Head Enterprises logo and words identifying Head Enterprises. In using the links, you agree that you will take full responsibility in maintaining all such links. All subscription Sites shall display such graphic images prominently throughout your site as you see fit and with our consent. You shall not alter, modify, or expand the links in any way without our written consent. Each link connecting users of your web site to our web site will in no way alter the look, feel, or functionality of our web site. We have the right in our sole discretion to monitor your web site at any time and from time to time to determine if you are in compliance with the terms of this Agreement.</p>
<p>Subscriber should place the appropriate copyright and trademark notices.</p>
<p>You are allowed to use the prices of the Head Enterprises products on your web site but you are responsible for keeping your information on pricing up-to-date as Head Enterprises from time to time will post specials, discounts or change product pricing in their sole discretion.</p>
<ol>
    <li>Order Processing.</li> </ol>
<p>We will be responsible for providing all information necessary to allow you to make appropriate links from your web site to our web site. However, all links must be approved by Head Enterprises. We will process orders placed by customers who follow the links from your web site to the Head Enterprises web site. We reserve the right to reject orders that do not comply with certain requirements that we periodically may establish. We will be solely responsible for all aspects of order processing and fulfillment, including order entry, payment processing, shipping and handling, cancellations, returns and related customer service. We will track the volume and amount of sales generated by your web site and will make unaudited reports available for your review through your subscription account on our web site. The form, content, and frequency of the reports may vary from time to time to our discretion. To permit accurate tracking, reporting, and fee accrual, you must ensure that the links between your web site and our web site are properly formatted. It is your sole responsibility to ensure that the links that you have placed on your web site are always working properly.</p>
<ol> <li>Bonus.</li>
</ol>
<p>Bonus (Bonus Rate) on tractable online sales are paid on net sales (i.e., the net is the remaining amount after any of these deductions: sales tax, duty, shipping, handling, credit card fees and similar charges, and not including any portion of payment made through the redemption of gift certificates, coupons, or credits. The Bonus Rate is subject to change at any time or from time to time, in our sole and absolute discretion. You will be notified of any change in the Bonus Rate. Bonus will also be reduced for amounts due to credit card fraud, bad debts, cancellations, charge backs and credits for returned goods. A commission will be paid only if the visitor to our web site is tracked by the system from the time of the link to the time of the sale. No commission will be paid if the visitor to our web site cannot be tracked by our system.</p>
<p>Our cookies are non-expiring, so repeat visitors that do not come directly from your web site will still count toward your Bonus if the cookie is not otherwise removed by the user. For a sale to generate a commission the customer must follow the link from your web site to our web site, purchase the Product or Products in question using our online ordering system, accept delivery of the item at the shipping destination, and remit full payment to us.</p>
<ol>
    <li>Bonus Payment.</li>
</ol>
<p>Bonuses on sales are paid on net sales actually collected from customers. Orders are not eligible for a commission due to credit card fraud, bad debts, cancellations, charge backs and credits for returned Products. If a commission has been paid, the commission will be deducted from future Bonus. Bonus will be paid 30 days after the order is fulfilled. All Bonuses are paid at the end of any given month. The Bonus base is subject to change at any time or from time to time, in our sole and absolute discretion. You will be notified of any change in the Bonus base.</p>
<p>All Bonus payments are made through PayPal.com unless special arrangements are made for subscribers who do not have access to PayPal.com.</p>
<p>You agree that you are solely responsible for all tax obligations due to all taxing authorities arising from or in connection with your participation in our subscription Program. Head Enterprises shall not withhold any taxes of any kind from your commission checks.</p>
<p>Head Enterprises is not responsible for resending lost or missing payments past 90 days from payment date.</p>
<ol>
    <li>Reports of Sales.</li>
</ol>
<p>You will be given a password and have the ability to enter a password-protected web site to receive your sales statistics on a daily basis.</p>
<ol>
    <li>Policies and Pricing.</li>
</ol>
<p>Subscribers who sponsor other subscribers or review telephone ads through the subscription Program will be deemed to be subscribers of Head Enterprises. Accordingly, all Head Enterprises rules, policies, and operating procedures concerning customer orders, customer service, and sales will apply to those subscribers. We may change our policies and operating procedures at any time. For example, we will determine the prices to be charged for ads viewed in the subscription Program in accordance with our own pricing policies. Viewing prices and availability may vary from time to time We will use commercially reasonable efforts to present accurate information, but we cannot guarantee the availability or price of any particular ad view.</p>
<ol>
    <li>Non-Exclusive Limited License and Use of Head Enterprises Logos and Trademarks.</li>
</ol>
<p>We grant you a non-exclusive, non-transferable, revocable right to (i) access our web site through links solely in accordance with the terms of this Agreement, and (ii) solely in connection with such links, to use our logos, trade names, trademarks and similar identifying material (collectively " Marks"), solely for the purpose of selling Product on your web site for Head Enterprises. You may not alter, modify, or change the Head Enterprises logos, trademarks or any other text content provided to you through the Head Enterprises subscription section. The use of any of the logos, trademarks or text content are only extended to members in good standing in the Head Enterprises subscription Program.</p>
<p>If you see logos, trademarked items or text content that is not in the materials available to subscriptions in the marketing section and you wish to use on your web site, you may not use them without prior written permission. Permission is not to be construed as Head Enterprises giving you any legal ownership or rights to these logos, trademarks, or text content. Head Enterprises’s own use of any logos, trademarks, or text content in the display or marketing of Head Enterprises products does not automatically make it acceptable for subscriptions to assume usage of same materials is considered acceptable use of such materials for promotion of Head Enterprises products. Subscribers should assume that ONLY materials directly made available from Head Enterprises to subscription for the purpose of selling product for Head Enterprises shall be acceptable to use.</p>
<p>The rights granted to you pursuant to this section shall terminate upon the effective date of the expiration or termination of this Agreement.</p>
<p>Additionally, we reserve the right to secure the highest position in pay-per-click and pay-per-position search engines and advertising sites by submitting a bid for URLs or other search terms considered as trademarks, sales marks, service marks, registered trademarks, or registered URLs (or any variations or abbreviations of same) of Head Enterprises. At no time shall you submit bids or use other methods that would cause listings for your site to rank higher than Head Enterprises rankings for trademarks, sales marks, service marks, registered trademarks, or registered URLs (or any variations or abbreviations of same) of Head Enterprises.</p>
<ol>
    <li>Publicity, Email, and Spam Policies.</li>
</ol>
<p>You shall not create, publish, distribute or permit any written material that makes reference to Head Enterprises, without first submitting such material to us and receiving our written consent.</p>
<p>Be careful about your advertising methods using email. Head Enterprises will not tolerate any forms of Spam. We will hear both sides of a Spam complaint but we will remove one subscription before we risk all subscriptions losing email privileges. In the event an subscription is charged with spamming
    practices, Head Enterprises shall not be held liable for any legal action taken against said subscription nor be financially responsible for fines owed by said subscription.</p>
<ol>
    <li>Responsibility for Your Site.</li>
</ol>
<p>You will be solely responsible for the development, operation, and maintenance of your web site and for all materials that appear on your web site. We shall have no responsibility for the development, operation, and maintenance of your web site and for all materials that appear on your web site. You hereby represent and warrant to us that materials posted on your web site do not violate or infringe upon the rights of any third party (including, for example, copyrights, trademarks, privacy, or other personal or proprietary rights), and that materials posted on your web site are not libelous or otherwise illegal. You must have express permission to use copyrighted material owned by another party or other proprietary material. We will not be responsible if you use copyrighted material from another party or other proprietary material in violation of the law.</p>
<ol>
    <li>Term of the Agreement.</li>
</ol>
<p>The term of this Agreement will begin when your subscription application has been received by Head Enterprises through the Head Enterprises web site and you have accepted the Terms and Conditions in this Agreement. This Agreement will end when terminated by either party. The Agreement may be terminated by Head Enterprises or the subscriber for any reason upon thirty (30) days prior email or written notice, or immediately upon notice of any breach of the provisions of this Agreement. Upon termination you may no longer use Head Enterprises banners, images, content, trademarks, etc., on your web site, or provide hyperlinks to the Head Enterprises web site. If this Agreement is terminated because you have violated the terms of this Agreement or if this Agreement is terminated because your web site becomes subject to the Content Restrictions set forth in Section 1, you are not eligible to receive any commission payments, even for Bonus earned prior to the date of termination. If this
    Agreement is terminated for any other reason, you are eligible to earn a bonus only on sponsoring and ad viewing occurring during the term of the Agreement, and Bonus earned through the date of termination will remain payable only if the related orders are not canceled or returned. We reserve the right to withhold your final payment for a reasonable time to ensure that the correct amount is paid.</p>
<ol> <li>Modification.</li>
</ol>
<p>We may modify any of the terms and conditions contained in this Agreement, at any time and in our sole discretion. Notice of any change by email to your address on our records, or the posting on our web site of a change notice or a new agreement, is considered sufficient notice for notifying you of a modification to the terms and conditions of this Agreement. Modifications may include, but are not limited to, changes in the scope of available commission fees, commission schedules, payment procedures, and subscription Program rules. All such modifications shall take effect 48 hours after we serve notice as provided above, unless we indicate otherwise. If any modification is unacceptable to you, your only recourse is to terminate this Agreement. Your continued participation in the subscription Program, following our posting of a change notice or new agreement on our web site, will constitute binding acceptance of the change.</p>
<ol>
    <li>Relationship of Parties.</li>
</ol>
<p>You and Head Enterprises are independent contractors, and nothing in this Agreement will create any partnership, joint venture, agency, franchise, sales representative, or employment relationship between the parties. You will have no authority to make or accept any offers or representations on our behalf. You will not make any statement, whether on your site or otherwise, that reasonably would contradict anything in this Section.</p>
<ol>
    <li>Limitation of Liability.</li>
</ol>
<p>We will not be liable for indirect, incidental, special, or consequential punitive or multiple damages, including without limitation any damages resulting from loss of use, loss of business, loss of revenue, loss of profits, or loss of data arising in connection with this Agreement, the subscription Program, or Head Enterprises performance of services or of any other obligations relating to the Agreement, even if we have been advised of the possibility of such damages. Further, our aggregate liability arising with respect to this Agreement and the subscription Program will not exceed the total Bonus paid or payable to you under this Agreement.</p>
<p>The foregoing limitation of liability shall apply regardless of the cause of action under which such damages are sought.</p>
<ol> <li>Disclaimers.</li>
</ol>
<p>We make no express or implied warranties or representations with respect to the subscription Program or any Product or other items sold through the subscription Program (including, without limitation, warranties of fitness for a particular purpose, merchantability, non-infringement, or any implied warranties arising out of a course of performance, dealing, or trade usage). In addition, we make no representation that the operation of our web site will be uninterrupted or error-free, and we will not be liable for the consequences of any interruptions or errors.</p>
<ol>
    <li>Representations and Warranties.</li> </ol>
<p>You hereby represent and warrant to us that this Agreement has been duly and validly executed and delivered by you and constitutes your legal, valid and binding obligation, enforceable against you in accordance with its terms; and that the execution, delivery and performance by you of this Agreement are within your legal capacity and power; have been duly authorized by all requisite action on your part; require the approval or consent of no other persons; and neither violate nor constitute a default under the (i) provision of any law, rule, regulation, order, judgment, or decree to which you are subject or which is binding upon you, or (ii) the terms of any other agreement, document, or instrument applicable to you or binding upon you.</p>
<ol> <li>Confidentiality.</li>
</ol>
<p>We may disclose to you certain information as a result of your participation as part of the subscription Program, which information we consider to be confidential (herein referred to as "Confidential Information"). For purposes of this Agreement, the term "Confidential Information" shall include, but not be limited to, any modifications to the terms and provisions of this subscription Program Agreement made specifically for your site and not generally available to other members of the subscription Program, web site, business and financial information relating to Head Enterprises, customer and vendor lists relating to Head Enterprises, and pricing and sales information for Head Enterprises and any members of the subscription Program other than you. Confidential Information shall also include any information that we designate as confidential during the term of this Agreement.</p>
<p>You agree not to disclose any Confidential Information and that such Confidential Information shall remain strictly confidential and secret and shall not be utilized, directly or indirectly, by you for your own business purposes or for any other purpose except and solely to the extent that any such information is generally known or available to the public or if same is required by law or legal process. We make no warranty, expressed or implied, with respect to any information delivered hereunder,
    including implied warranties of merchantability, fitness for a particular purpose or freedom from patent, trademark or copyright infringements, whether arising by law, custom or conduct, or as to the accuracy or completeness of the information and we shall not have any liability to you or to any other person resulting from your or third-party use of the information.</p>
<ol> <li>Indemnification.</li>
</ol>
<p>You hereby agree to indemnify, defend, and hold harmless Head Enterprises, its shareholders, officers, directors, employees, agents, subscriptions, successors and assigns, from and against any and all claims, demands, losses, liabilities, damages or expenses (including attorney fees and costs) of any nature whatsoever incurred or suffered by us (collectively the "Losses"), in so far as such Losses (or actions in respect thereof) arise out of, are related to, or are based on (i) any claim or threatened claim that our use of the subscription Trademarks infringes on the rights of any third party; (ii) the breach of any representation or warranty made by you herein; or (iii) or any claim related to your web site.</p>
<ol>
    <li>Independent Investigation.</li>
</ol>
<p>YOU ACKNOWLEDGE THAT YOU HAVE READ THIS AGREEMENT AND AGREE TO ALL ITS TERMS AND CONDITIONS. YOU UNDERSTAND THAT WE MAY AT ANY TIME (DIRECTLY OR INDIRECTLY) SOLICIT CUSTOMER REFERRALS ON TERMS THAT MAY DIFFER FROM THOSE CONTAINED IN THIS AGREEMENT OR OPERATE WEB SITES THAT ARE SIMILAR TO OR COMPETITIVE WITH YOUR WEB SITE. YOU HAVE INDEPENDENTLY EVALUATED THE DESIRABILITY OF PARTICIPATING IN THE Subscription PROGRAM AND ARE NOT RELYING ON ANY REPRESENTATION, GUARANTEE, OR STATEMENT OTHER THAN AS SET FORTH IN THIS AGREEMENT.</p>
<ol> <li>Miscellaneous.</li>
</ol>
<p>This Agreement will be governed by the laws of the United States and the State of California, without reference to rules governing choice of laws. Any action relating to this Agreement must be brought in the federal or state courts located in Riverside, California and you irrevocably consent to the jurisdiction of such courts. You may not assign this Agreement, by operation of law or otherwise, without our prior written consent. Subject to that restriction, this Agreement will be binding on, inure to the benefit of, and enforceable against the parties and their respective successors and assigns. Our failure to enforce your strict performance of any provision of this Agreement will not constitute a waiver of our right to subsequently enforce such provision or any other provision of this Agreement.</p>
<p>THIS IS A LEGAL AGREEMENT BETWEEN YOU AND Head Enterprises. BY CLICKING THE "I ACCEPT" BUTTON IN THE SUBSCRIPTION APPLICATION YOU ARE AFFIRMATIVELY STATING THAT YOU HAVE READ AND UNDERSTAND THE TERMS SET FORTH HEREIN AND ARE AFFIRMATIVELY INDICATING YOUR ACCEPTANCE OF THIS SUBSCRIPTION NETWORK AGREEMENT AND YOU AGREE TO BE BOUND BY THE TERMS HEREOF.</p>
<p>If you agree, then sign up as a Head Enterprises subscriber!</p>

</article>
            </div>

  </section>
@include('layouts.partials.footer')
@stop
