name: Issues

on:
  issues:
    types: [labeled]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  issues: write

jobs:
  help-wanted:
    uses: laravel/.github/.github/workflows/issues.yml@main
