name: Update Changelog

on:
  release:
    types: [released]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions: {}

jobs:
  update:
    permissions:
      contents: write
    uses: laravel/.github/.github/workflows/update-changelog.yml@main
